apiVersion: v1
kind: Pod
metadata:
  name: memcached
spec:
  containers:
  - name: app
    image: memcached
    ports:
    - containerPort: 11211
    resources:
      requests:
        cpu: 350m
        memory: 150Mi
      limits:
        cpu: 500m
        memory: 250Mi